### ISSUE TITLE
Why is this not published as @types/rimraf?

### ISSUE THREAD

**Issue by cliffkoh** [typed-typings/npm-rimraf#1]
Hi,

I'm a little confused... why is this not published as @types/rimraf but instead sitting here? The DefinitelyTyped version is for a really old version of rimraf...

Thanks!

**Comment by blakeembrey** [comment]
Because we don't have access to publish on NPM, that's owned by MicroSoft. See https://github.com/Microsoft/types-publisher/issues/4. Feel free to complain to MicroSoft instead 😄 

All @types modules are currently available using Typings only.
